### ISSUE TITLE
Two minor bugs in list types

### ISSUE THREAD

**Issue by torogi94** [FAIRChemistry/md-models#7]
I noticed the following two bugs when working with list types in markdown:  

1. HTML links to type definitions only work with non-list types but when used with list types, the model generation breaks.
2. The previous way of defining list types, `Multiple: True`, does not work anymore, but also does not result in a validation error. The CLI just ignores this statement altogether and silently creates the equivalent non-list type in the output API.

Example code for bug 1:
```
MyObject
- my_field
  - Type: [AnotherObject[]](#anotherobject)
```

Unexpected output:
```
  ...
  ERROR mdmodels::validation > [MyObject] TypeError: Type  of property my_field not found. Either define the type or use a base type.
Error: "Invalid Markdown Model"
```

Example code for bug 2:
```
MyObject
- my_field
  - Type: AnotherObject
  - Multiple: True
```

Unexpected output:
```
...
my_field: Optional[AnotherObject] = Field(default=None)
```

**Comment by JR-1991** [comment]
Thank you for your submission! The first issue can be resolved by adding brackets at the end `[]` of the link. I recall that this change was made intentionally to preserve the link functionality of markdown. Therefore, your example would be modified to the following:

```
- my_field
  - Type: [AnotherObject](#anotherobject)[]
```

Regarding the second issue, this will be implemented within the branch linked to this issue and will be shipped in version 1.1.2.
